<Button>:
    font_size: 40
    color: 0.3, 0.6, 0.7, 1    #color, color, opacity
    size_hint: 0.3, 0.5  #30% width, 50%height

<FloatLayout>:
    Button:
        pos_hint: {"x": 0.5, "top": 1} #"bottom":0, "right":0, "left":0 }
        text: "Tech With"

    Button:
        id: btn
        pos_hint: {"y":0.3}
        text: "Tim" if btn.state == "normal" else "Down"
        background_color: 0.3, .4, .5, 1
